from collections import defaultdict
from pathlib import Path
import re

REPORT_PATH = Path("visual_fingerprint_report.txt")
SUMMARY_PATH = Path("visual_fingerprint_summary.txt")
PAIR_HEADER = re.compile(r"^=== Exact matches \(Distance 0\): (.+?) ===$")
PATH_LINE = re.compile(r"^  (.+\.(?:jpg|jpeg|png|bmp|webp))$", re.IGNORECASE)


def normalized_name(path_text):
    filename = Path(path_text).stem
    return re.split(r"_jpg", filename, maxsplit=1, flags=re.IGNORECASE)[0].lower()


def parse_report(text):
    sections = {}
    current_pair = None
    current_matches = []
    pending_paths = []

    def save_current():
        if current_pair is not None:
            sections[current_pair] = current_matches.copy()

    for line in text.splitlines():
        header = PAIR_HEADER.match(line)
        if header:
            save_current()
            current_pair = header.group(1)
            current_matches = []
            pending_paths = []
            continue

        if line.startswith("=== "):
            save_current()
            current_pair = None
            current_matches = []
            pending_paths = []
            continue

        if current_pair is None:
            continue

        path_match = PATH_LINE.match(line)
        if path_match:
            pending_paths.append(path_match.group(1))
            if len(pending_paths) == 2:
                first_path, second_path = pending_paths
                current_matches.append((first_path, second_path))
                pending_paths = []

    save_current()
    return sections


def main():
    sections = parse_report(REPORT_PATH.read_text(encoding="utf-8"))
    lines = [
        "VISUAL FINGERPRINT SUMMARY FROM EXISTING REPORT",
        f"Source report: {REPORT_PATH.resolve()}",
        "",
        "Confirmed duplicate rule:",
        "  pHash distance = 0 AND normalized names match before _jpg (case-insensitive).",
        "  The .rf.<hash> suffix is ignored because it is generated by Roboflow.",
        "",
        "DATASET PAIR SUMMARY",
    ]

    all_confirmed = []
    for pair, matches in sections.items():
        confirmed = []
        name_mismatch = []
        for first_path, second_path in matches:
            first_name = normalized_name(first_path)
            second_name = normalized_name(second_path)
            record = (first_path, second_path, first_name, second_name)
            if first_name == second_name:
                confirmed.append(record)
                all_confirmed.append((pair, record))
            else:
                name_mismatch.append(record)

        lines.append(
            f"{pair} | distance_0={len(matches)} | "
            f"confirmed_overlap={len(confirmed)} | "
            f"name_mismatch={len(name_mismatch)}"
        )

    lines.extend([
        "",
        "RECOMMENDED DEDUPLICATION CANDIDATES",
        "Remove or reconcile only the confirmed overlaps below after checking annotations.",
        "Do not remove pairs listed only as name mismatches without visual/annotation review.",
    ])

    by_pair = defaultdict(list)
    for pair, record in all_confirmed:
        by_pair[pair].append(record)

    if not by_pair:
        lines.append("No confirmed overlaps found.")
    else:
        for pair, records in by_pair.items():
            lines.append(f"\n{pair}: {len(records)} confirmed overlap(s)")
            for first_path, second_path, normalized_first, _ in records:
                lines.append(f"  normalized_name: {normalized_first}")
                lines.append(f"    {first_path}")
                lines.append(f"    {second_path}")

    lines.extend([
        "",
        "IMPORTANT LIMITATION",
        "The source report records every distance-0 pair, but only the 30 closest nonzero",
        "(fuzzy) pairs for each dataset pair. Therefore this summary is complete for exact",
        "matches, but it cannot classify every nonzero image pair without rerunning the hash",
        "comparison or creating a fuller pairwise output.",
    ])

    SUMMARY_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Summary written to: {SUMMARY_PATH.resolve()}")
    print(f"Dataset pairs parsed: {len(sections)}")
    print(f"Confirmed overlaps: {len(all_confirmed)}")


if __name__ == "__main__":
    main()
